runtime: go112
api_version: go1

handlers:
- url: /.*
  script: _go_app

skip_files:
  - .*\.md
  - .*\.sh
  - ^\..*
  - Dockerfile
  - Gopkg\.*
  - LICENSE
  - Makefile
  - ^cuedescriptionstoascii$
  - ^vendor$
